/**:
  ros__parameters:
    antiwindup_cte : 3.0
    alpha: 0.2
    position_following:
      position_Kp: 
        x: 1.5
        y: 1.5
        z: 1.5
      position_Ki:
        x: 0.1
        y: 0.1
        z: 0.1
      position_Kd: 
        x: 0.0
        y: 0.0
        z: 0.0
    yaw_speed_controller:
      Kp: 1.0
      Ki: 0.001
      Kd: 0.0