/**:
  ros__parameters:
    base_frame: ""
    speed_limit: 
        vx: 1.0
        vy: 1.0
        vz: 1.0
    base:
      proportional_limitation : true
      target_twist_alpha: 0.01
      target_pose_predict_factor: 0.0
      target_height_alpha: 0.01
    pickup:
      target_topic: "object_pose"
      gripper_state_topic: "gripper/contacts/bottom"
      gripper_actuator_topic: "open_box"
      pickup_approach_2D_threshold: 0.05
      pickup_approach_height_threshold: 0.1
      pickup_approach_speed_threshold: 0.2
      gripper_height: 0.04
      vessel_height: 8.0
    unpick:
      target_topic: "aruco_pose"
      gripper_state_topic: "gripper/contacts/bottom"
      gripper_actuator_topic: "open_box"
      unpick_approach_2D_threshold: 0.5
      unpick_approach_height_threshold: 0.3
      unpick_approach_speed_threshold: 0.4
      gripper_height: 0.0
      vessel_height: 5.0
      object_height: 0.3
      delivery_height: 1.5
    dynamicFollow:
      target_topic: "vessel_target/computed"
      height: 10.0
      distance: 0.5
      const_height: false

